# Generated by Django 4.2 on 2023-07-19 14:09

import MMSapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=MMSapp.models.filepaths)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('father', models.CharField(max_length=12)),
                ('mother', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=50)),
                ('Snumber', models.CharField(max_length=50)),
                ('Gnumber', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('class10thYear', models.CharField(max_length=80)),
                ('board10', models.CharField(max_length=12)),
                ('total1', models.CharField(max_length=100)),
                ('sscObtained', models.CharField(max_length=50)),
                ('percentageOutput', models.CharField(max_length=50)),
                ('class12thYear', models.CharField(max_length=80)),
                ('board12', models.CharField(max_length=50)),
                ('total4', models.CharField(max_length=10)),
                ('mark5', models.CharField(max_length=10)),
                ('percentageOutput1', models.CharField(max_length=10)),
                ('graduationYear', models.CharField(max_length=80)),
                ('collegeName', models.CharField(max_length=12)),
                ('graduationTotal', models.CharField(max_length=100)),
                ('graduationMark', models.CharField(max_length=50)),
                ('percentageOutput2', models.CharField(max_length=50)),
                ('stream12th', models.CharField(max_length=80)),
            ],
        ),
    ]
