# Generated by Django 4.2 on 2023-07-26 08:24

import MMSapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSapp', '0002_admissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allstudentsadmissionlist',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to=MMSapp.models.filepaths)),
                ('Unique_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=12)),
                ('mothername', models.CharField(max_length=100)),
                ('Permanent_Address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Snumber', models.CharField(max_length=50)),
                ('Gnumber', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=80)),
                ('Religion', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('SSCyear', models.CharField(max_length=80)),
                ('SSCBoard', models.CharField(max_length=50)),
                ('t1', models.CharField(max_length=100)),
                ('m1', models.CharField(max_length=50)),
                ('p1', models.CharField(max_length=50, null=True)),
                ('HSCyear', models.CharField(max_length=80)),
                ('HSCboard', models.CharField(max_length=50)),
                ('t2', models.CharField(max_length=10)),
                ('m2', models.CharField(max_length=10)),
                ('p2', models.CharField(blank=True, max_length=10, null=True)),
                ('graduationYear', models.CharField(max_length=80)),
                ('Collegename', models.CharField(max_length=12)),
                ('t3', models.CharField(max_length=100)),
                ('m3', models.CharField(max_length=50)),
                ('p3', models.CharField(blank=True, max_length=50, null=True)),
                ('HSCstream', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='admissionForm',
        ),
    ]
