# Generated by Django 4.2 on 2023-07-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMSapp', '0004_rename_fname_allstudentsadmissionlist_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstudentsadmissionlist',
            old_name='Unique_id',
            new_name='id',
        ),
    ]
