# Generated by Django 4.2 on 2023-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSapp', '0005_rename_unique_id_allstudentsadmissionlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudentsadmissionlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
