# Generated by Django 4.2 on 2023-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSapp', '0007_allstudentsadmissionlist_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudentsadmissionlist',
            name='application_number_integer',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
